GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJOaWtlbiBSaXJpIiwiZW1haWwiOiJuaWtlbnJpcmlAZ21haWwuY29tIiwiaWF0IjoxNjg1NDE5NDA4LCJleHAiOjE2ODU0MTk0Mjh9.s-36soJ70AqiUS_U-Bvu_HMl_2T8lTUt4pYgLrLBjrM

###
GET http://localhost:3001/token

###
POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "Niken Riri",
    "email": "nikenriri@gmail.com",
    "password": "1234567",
    "confPassword": "1234567"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "nikenriri@gmail.com",
    "password": "1234567"
}

###
DELETE http://localhost:3001/logout

